### ISSUE TITLE
Possible moves highlight texture is drawn multiple times

### ISSUE THREAD

**Issue by ParticlePeter** [ovgu-ccd/jchess#52] opened 2015-01-12 02:03 UTC
Boerd is not cleared when a player reselects another or the same piece of his own. All highlighted tiles stay on board.

**Comment by apfohl** [comment] 2015-01-12 21:36
@rheum could you close this issue with the commit that fixed this bug?

**Comment by rheum** [comment] 2015-01-15 18:20
Invalid. Duplicate of #55. Fixed previously.

**Closed by rheum** 2015-01-15 18:20 UTC
Labels: bug
